import { CartProvider } from "@/providers/CartProvider";
import Header from "@/components/Header";
import FooterOverlay from "@/components/FooterOverlay";
import StyledJsx from "@/components/StyledJsx";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StyledJsx />
      <body>
        <CartProvider>
          <Header />
          <div className="container">{children}</div>
        </CartProvider>
      </body>
    </html>
  );
}
